# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/interface/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parametersGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.parametersGroup.setObjectName("parametersGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.parametersGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parametersLabel = QtWidgets.QLabel(self.parametersGroup)
        self.parametersLabel.setObjectName("parametersLabel")
        self.verticalLayout_2.addWidget(self.parametersLabel)
        self.minQuantityLineEdit = QtWidgets.QLineEdit(self.parametersGroup)
        self.minQuantityLineEdit.setObjectName("minQuantityLineEdit")
        self.verticalLayout_2.addWidget(self.minQuantityLineEdit)
        self.maxQuantityLineEdit = QtWidgets.QLineEdit(self.parametersGroup)
        self.maxQuantityLineEdit.setObjectName("maxQuantityLineEdit")
        self.verticalLayout_2.addWidget(self.maxQuantityLineEdit)
        self.componentNameLineEdit = QtWidgets.QLineEdit(self.parametersGroup)
        self.componentNameLineEdit.setObjectName("componentNameLineEdit")
        self.verticalLayout_2.addWidget(self.componentNameLineEdit)
